FROM oven/bun:1-alpine

WORKDIR /usr/src/app 

ARG DATABASE_URL
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web 
COPY ./packages ./packages 

ENV DATABASE_URL=$DATABASE_URL
RUN bun install
RUN bun run db:generate
RUN bun run build

EXPOSE 3000
 
CMD [ "bun", "run", "start:web" ]